# Generated by Django 4.2.7 on 2023-11-04 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='f_creation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
