# Generated by Django 4.2.7 on 2023-11-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_f_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='a',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
