# Generated by Django 4.2.7 on 2023-11-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='a',
            new_name='creation_at',
        ),
    ]
